#!/usr/bin/env bash
# Installing Nginx and redirection for /redirect_me to redirect to another page

# Update package list for nginx
apt-get -y update

# Install Nginx on my server
apt-get -y install nginx

# Allow HTTP traffic through the firewall
ufw allow 'Nginx HTTP'

# Create a simple "Hello World!" page at root
echo "Hello World!" > /var/www/html/index.html

# Start the Nginx service
service nginx start

# Add a redirection configuration to Nginx
sed -i "25i location /redirect_me {\n return 301 https://www.youtube.com/watch?v=v5nfmtFzvvk;\n}\n" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
