#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
# the page contains the string Ceci n'est pas une page
apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page." > /var/www/html/404.html
service nginx start
sed -i "25i location /redirect_me {\n return 301 https://www.youtube.com/watch?v=v5nfmtFzvvk;\n}\n" /etc/nginx/sites-available/default
sed -i "28i error_page 404 /404.html;\n location = /404.html {\n root /var/www/html;\n internal;\n}\n" /etc/nginx/sites-available/default
service nginx restart
