#!/usr/bin/env bash
# configuring second web server for load balancing 
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
# echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
service nginx start
sed -i "28i error_page 404 /404.html;\n location = /404.html {\n root /var/www/html;\n internal;\n}\n" /etc/nginx/sites-available/default
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
service nginx restart
