#!/usr/bin/env bash
# a script to configure 
apt-get -y update
apt-get -y install haproxy
sed -i -e "\$aENABLED=1" /etc/default/haproxy
sed -i -e "\$afrontend http\n\tbind *:80\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver  314859-web-01 18.206.208.154:80 check\n\tserver 314859-web-02 100.26.236.42:80 check" /etc/haproxy/haproxy.cfg
service haproxy restart
