#!/usr/bin/env bash
# bash script to configiure ports host name with IPS
cp /etc/hosts ~/hosts.new
echo "127.0.0.1 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
