#!/usr/bin/env bash
# using apache to run on container and return message
#echo "Hello Holberton" >> /etc/apache2.conf
#service apache2 start

apt-get update
apt-get install -y apache2
service apache2 start
