#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2 #chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start

